#[derive(Debug, Clone, Copy)]
pub struct Object {
    pub class: ObjectClass,
    pub confidence: f32,
    pub bbox: BoundingBox,
}

#[derive(Debug, Clone, Copy)]
pub struct BoundingBox {
    pub x1: f32, // X upper left (px)
    pub y1: f32, // Y upper left (px)
    pub x2: f32, // X lower right (px)
    pub y2: f32, // Y lower right (px)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ObjectClass {
    Person,
    Bicycle,
    Car,
    Motorcycle,
    Airplane,
    Bus,
    Train,
    Truck,
    Boat,
    TrafficLight,
    FireHydrant,
    StopSign,
    ParkingMeter,
    Bench,
    Bird,
    Cat,
    Dog,
    Horse,
    Sheep,
    Cow,
    Elephant,
    Bear,
    Zebra,
    Giraffe,
    Backpack,
    Umbrella,
    Handbag,
    Tie,
    Suitcase,
    Frisbee,
    Skis,
    Snowboard,
    SportsBall,
    Kite,
    BaseballBat,
    BaseballGlove,
    Skateboard,
    Surfboard,
    TennisRacket,
    Bottle,
    WineGlass,
    Cup,
    Fork,
    Knife,
    Spoon,
    Bowl,
    Banana,
    Apple,
    Sandwich,
    Orange,
    Broccoli,
    Carrot,
    HotDog,
    Pizza,
    Donut,
    Cake,
    Chair,
    Couch,
    PottedPlant,
    Bed,
    DiningTable,
    Toilet,
    Tv,
    Laptop,
    Mouse,
    Remote,
    Keyboard,
    CellPhone,
    Microwave,
    Oven,
    Toaster,
    Sink,
    Refrigerator,
    Book,
    Clock,
    Vase,
    Scissors,
    TeddyBear,
    HairDrier,
    Toothbrush,
    Unknown,
}

impl From<&str> for ObjectClass {
    fn from(name: &str) -> Self {
        match name {
            "person" => Self::Person,
            "bicycle" => Self::Bicycle,
            "car" => Self::Car,
            "motorcycle" => Self::Motorcycle,
            "airplane" => Self::Airplane,
            "bus" => Self::Bus,
            "train" => Self::Train,
            "truck" => Self::Truck,
            "boat" => Self::Boat,
            "traffic light" => Self::TrafficLight,
            "fire hydrant" => Self::FireHydrant,
            "stop sign" => Self::StopSign,
            "parking meter" => Self::ParkingMeter,
            "bench" => Self::Bench,
            "bird" => Self::Bird,
            "cat" => Self::Cat,
            "dog" => Self::Dog,
            "horse" => Self::Horse,
            "sheep" => Self::Sheep,
            "cow" => Self::Cow,
            "elephant" => Self::Elephant,
            "bear" => Self::Bear,
            "zebra" => Self::Zebra,
            "giraffe" => Self::Giraffe,
            "backpack" => Self::Backpack,
            "umbrella" => Self::Umbrella,
            "handbag" => Self::Handbag,
            "tie" => Self::Tie,
            "suitcase" => Self::Suitcase,
            "frisbee" => Self::Frisbee,
            "skis" => Self::Skis,
            "snowboard" => Self::Snowboard,
            "sports ball" => Self::SportsBall,
            "kite" => Self::Kite,
            "baseball bat" => Self::BaseballBat,
            "baseball glove" => Self::BaseballGlove,
            "skateboard" => Self::Skateboard,
            "surfboard" => Self::Surfboard,
            "tennis racket" => Self::TennisRacket,
            "bottle" => Self::Bottle,
            "wine glass" => Self::WineGlass,
            "cup" => Self::Cup,
            "fork" => Self::Fork,
            "knife" => Self::Knife,
            "spoon" => Self::Spoon,
            "bowl" => Self::Bowl,
            "banana" => Self::Banana,
            "apple" => Self::Apple,
            "sandwich" => Self::Sandwich,
            "orange" => Self::Orange,
            "broccoli" => Self::Broccoli,
            "carrot" => Self::Carrot,
            "hot dog" => Self::HotDog,
            "pizza" => Self::Pizza,
            "donut" => Self::Donut,
            "cake" => Self::Cake,
            "chair" => Self::Chair,
            "couch" => Self::Couch,
            "potted plant" => Self::PottedPlant,
            "bed" => Self::Bed,
            "dining table" => Self::DiningTable,
            "toilet" => Self::Toilet,
            "tv" => Self::Tv,
            "laptop" => Self::Laptop,
            "mouse" => Self::Mouse,
            "remote" => Self::Remote,
            "keyboard" => Self::Keyboard,
            "cell phone" => Self::CellPhone,
            "microwave" => Self::Microwave,
            "oven" => Self::Oven,
            "toaster" => Self::Toaster,
            "sink" => Self::Sink,
            "refrigerator" => Self::Refrigerator,
            "book" => Self::Book,
            "clock" => Self::Clock,
            "vase" => Self::Vase,
            "scissors" => Self::Scissors,
            "teddy bear" => Self::TeddyBear,
            "hair drier" => Self::HairDrier,
            "toothbrush" => Self::Toothbrush,
            _ => Self::Unknown,
        }
    }
}

impl std::fmt::Display for ObjectClass {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl std::fmt::Display for Object {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{} ({:.0}%)", self.class, self.confidence * 100.0)
        // write!(
        //     f,
        //     "{} ({:.0}%) [{:.1}, {:.1}] -> [{:.1}, {:.1}]",
        //     self.class,
        //     self.confidence * 100.0,
        //     self.bbox.x1,
        //     self.bbox.y1,
        //     self.bbox.x2,
        //     self.bbox.y2,
        // )
    }
}
