[package]
name = "onvif-events-telegram"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.89"
chrono = "0.4.38"
serde = "1.0.207"
serde_yaml = "0.9.34"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"

api-camera = { path = "../api-camera" }
app-core = { path = "../app-core" }
onvif = { path = "../onvif" }
repository = { path = "../repository" }
telegram = { path = "../telegram" }
ultralitics-detector = { path = "../ultralytics-detector"}
itertools = "0.15.0"
rand = "0.10.2"
