[package]
name = "onvif"
version = "0.1.0"
edition = "2021"

[dependencies]
onvif = { git = "https://github.com/lumeohq/onvif-rs", rev = "1b1e6fd" }
onvif-xsd = { git = "https://github.com/lumeohq/onvif-rs", rev = "1b1e6fd" }
# recording = { git = "https://github.com/lumeohq/onvif-rs", rev = "1b1e6fd" }
# replay = { git = "https://github.com/lumeohq/onvif-rs", rev = "1b1e6fd" }
# search = { git = "https://github.com/lumeohq/onvif-rs", rev = "1b1e6fd" }
schema = { git = "https://github.com/lumeohq/onvif-rs", rev = "1b1e6fd" }
xsd-types = { git = "https://github.com/lumeohq/xsd-parser-rs", rev = "7f3d433" }

anyhow = "1.0.86"
async-trait = "0.1.89"
chrono = "0.4.38"
futures-util = "0.3.30"
url = "2.2.0"
reqwest = "0.13.4"
tracing = "0.1"

app-core = { path = "../app-core" }
diqwest = "3.2.0"
