[package]
name = "telegram"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.89"
chrono = "0.4.38"
teloxide = { version = "0.13", features = ["macros"] }
tracing = "0.1"

app-core = { path = "../app-core" }
onvif = { path = "../onvif" }
repository = { path = "../repository" }
